### PR TITLE
Adds release script for smoother git releases

### PR DESCRIPTION
**Pull request by PuneetPunamiya**
This patch also adds a github action workflow, which
will be triggered when a new tag is pushed and the
workflow will run the script to do the pre-release

Signed-off-by: Puneet Punamiya ppunamiy@redhat.com

### CODE REVIEW

**Review by vdemeester — COMMENTED** [review]
So the main question is : Do we want a workflow that runs on tags (and publishes the release) or do we want a workflow that is able to create and build the release ?

**Comment by PuneetPunamiya** [comment]
> So the main question is : Do we want a workflow that runs on tags (and publishes the release) or do we want a workflow that is able to create and build the release ?
I would say we would need a workflow that would be able to create and build the release

Now I have got some question
1. I thought we need to manually just run the script and release is created
2. If we setup a workflow, I think we might have to configure and install some binaries like gh, git, ko and also some secret token to be able to push the git

**Comment by PuneetPunamiya** [comment]
> So the main question is : Do we want a workflow that runs on tags (and publishes the release) or do we want a workflow that is able to create and build the release ?


So now I have updated the pr with a workflow which will be triggered when a tag is pushed and that workflow will run a script to create a pre-release

**Review by vdemeester — APPROVED** [review]
/lgtm

**Pull request merged**
