### PR TITLE
Fixes config files

### PR DESCRIPTION
**Pull request by PuneetPunamiya**
Signed-off-by: Puneet Punamiya ppunamiy@redhat.com

### CODE REVIEW

**Comment by vdemeester** [comment]
We need to update the github workflow as well to use `config/kubernetes` now though, to fix the CI.

**Comment by PuneetPunamiya** [comment]
> We need to update the github workflow as well to use `config/kubernetes` now though, to fix the CI.

Updated

**Review by vdemeester — APPROVED** [review]
/lgtm

**Pull request merged**
